# Generated by Django 2.2 on 2019-05-15 23:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
                ('menu_titles', models.CharField(max_length=60, verbose_name='menu_title')),
                ('slug', models.CharField(default=core.models.Page.generate_slug, max_length=60, verbose_name='slug')),
            ],
        ),
    ]
