# Generated by Django 2.2.3 on 2019-09-14 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.IntegerField(choices=[(1, 'Primary'), (2, 'Secondary'), (3, 'Success'), (4, 'Info'), (5, 'Warning'), (6, 'Error'), (7, 'Light')], default=1, verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='FaIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=120, verbose_name='Style')),
            ],
        ),
        migrations.CreateModel(
            name='FaStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.IntegerField(choices=[(1, 'Solid'), (2, 'Regular'), (3, 'Light'), (4, 'Brand')], default=2, verbose_name='Icon Style')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('SP', 'Simple'), ('CB', 'Circle'), ('BB', 'Brand'), ('SBI', 'Split if Icon')], default='SP', max_length=3, verbose_name='Form')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('DB', 'Default'), ('SB', 'Small'), ('LG', 'Large')], default='DB', max_length=3, verbose_name='Size')),
            ],
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=20)),
                ('href', models.CharField(blank=True, max_length=120)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='example.Color')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='example.Form')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='example.FaIcon')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='example.Size')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='example.FaStyle')),
            ],
        ),
    ]
