# Generated by Django 2.2.3 on 2019-09-11 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('CB', 'Circle Buttons'), ('FB', 'Facebook Button'), ('GB', 'Google Button'), ('SBI', 'Split Buttons if Icon')], default='CB', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ButtonSubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_group', models.CharField(choices=[('DB', 'Default Buttons'), ('SB', 'Small Buttons'), ('LG', 'Large Buttons')], default='DB', max_length=3)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_groups', to='example.ButtonGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=20)),
                ('url', models.CharField(blank=True, max_length=120)),
                ('bootstrap_color', models.CharField(choices=[('btn-primary', 'Primary Button'), ('btn-secondary', 'Secondary Button'), ('btn-success', 'Success Button'), ('btn-info', 'Info Button'), ('btn-warning', 'Warning Button'), ('btn-danger', 'Danger Button'), ('btn-light', 'Light Button')], default='btn-primary', max_length=15)),
                ('sub_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='example.ButtonSubGroup')),
            ],
        ),
    ]
