# Generated by Django 2.2.3 on 2019-09-13 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FaIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_style', models.IntegerField(choices=[(1, 'Default'), (2, 'Small'), (3, 'Large'), (4, 'Large')], default=2, verbose_name='Icon Style')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('CB', 'Circle'), ('BB', 'Brand'), ('SBI', 'Split if Icon')], default='SP', max_length=3, verbose_name='Form')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('DB', 'Default'), ('SB', 'Small'), ('LG', 'Large')], default='DB', max_length=3, verbose_name='Size')),
            ],
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=20)),
                ('href', models.CharField(blank=True, max_length=120)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='example.Color')),
                ('fa_icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='example.FaIcon')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='example.Form')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='example.Size')),
            ],
        ),
    ]
